### ISSUE TITLE
Create logic for email sending based on process conditions

### ISSUE THREAD

**Issue by marookh** [mokolodi1/aesop-afghanistan#24]
**Proposed Solution:**
- Review and optimize the logic for determining when to send phone buddy and admin emails.
- Add a new line to the output sheet if the result was different from the last run and it was a robot. .

**TODO Comment Location:**
Located within the code snippet for email sending based on process conditions.

**Comment by mokolodi1** [comment]
Comment in the code:

> TODO: if the result was different from the last run (and it was a robot), add a new line to the output sheet

Deliverables: 
- [ ] When the script is run as a robot, it adds a new row to the database if the output is different from the last run
- [ ] The database contains the time and summary
- [ ] README documents behavior
