### ISSUE TITLE
 Improve Handling of Secrets and Credentials

### ISSUE THREAD

**Issue by marookh** [mokolodi1/aesop-afghanistan#26]
The codebase currently reads sensitive information, such as the spreadsheet ID, from a file located in the "secrets" . This approach poses security risks and lacks robust error identification mechanisms. The code includes a TODO comment to address this issue and consider a more secure secrets management system.

**Proposed Changes**:

- Identify and review all instances where sensitive information is read from files and improve the handling of secrets throughout the codebase.

- Evaluate and implement a more robust secrets management system, such as a secure vault, environment variables, or a dedicated secrets management tool.

- Enhance error identification and logging to improve the detection of issues related to secrets and credentials.

**Comment by marookh** [comment]
# TODO: Go to all the different places where we read from secrets and make it easier to identify errors.
# Consider employing a more robust secrets system than a set of files sitting on the disk ;)

**Comment by marookh** [comment]
```python
# TODO: Go to all the different places where we read from secrets and make it easier to identify errors.
# Consider employing a more robust secrets system than a set of files sitting on the disk ;)
```

**Comment by mokolodi1** [comment]
Deliverables: 
- [ ] `secrets` folder no longer needed
- [ ] `.env` file contains all secrets
- [ ] If a secret is missing, the script fails early in a way that makes it obvious what went wrong
- [ ] We have a documented process to share secrets (the `.env` file) between team members
- [ ] We have documentation as to what all the different secrets that are required are
